# Generated by Django 6.1.1 on 2026-09-11 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('outcome_trigger', models.CharField(choices=[('interested', 'Interested (Brochure & Offer)'), ('awaiting_followup', 'Awaiting Follow-up (Callback Confirmation)'), ('completed_followup', 'Completed Follow-up'), ('registered', 'Registered / Converted (Welcome & Booking)'), ('not_interested', 'Not Interested (Future Membership)'), ('lost', 'Lost / Junk'), ('escalation_day1', 'Day 1 Support Inaction Reminder'), ('escalation_day2', 'Day 2 Level 1 Manager Escalation Alert'), ('escalation_day3', 'Day 3 Manager Inaction Reminder'), ('escalation_day4', 'Day 4 Level 2 Admin Critical Escalation Alert'), ('reassignment_alert', 'Reassignment Alert to Staff')], max_length=50, unique=True)),
                ('template_body', models.TextField(help_text='Placeholders available: {guest_name}, {phone}, {followup_date_time}, {gallery_url}, {booking_code}, {staff_name}, {manager_name}, {hotel_name}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('instagram', 'Instagram Lead Ads'), ('whatsapp', 'WhatsApp Business'), ('facebook', 'Facebook Ads'), ('website', 'Website Form'), ('manual', 'Manual Entry')], default='website', max_length=20)),
                ('inquiry_details', models.TextField(blank=True, help_text='Room type, dates, budget, or inquiry notes')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('awaiting_followup', 'Awaiting Follow-up'), ('completed_followup', 'Completed Follow-up'), ('registered', 'Registered / Converted'), ('not_interested', 'Not Interested'), ('lost', 'Lost / Junk')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('followup_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_call_duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds of the latest call')),
                ('last_disposition_note', models.TextField(blank=True)),
                ('escalation_level', models.CharField(choices=[('normal', 'Normal'), ('day1_reminder', 'Day 1 Support Reminder (24h)'), ('level1_manager', 'Level 1 Manager Escalation (48h)'), ('day3_reminder', 'Day 3 Manager Reminder (72h)'), ('level2_admin', 'Level 2 Admin Critical (96h)')], db_index=True, default='normal', max_length=20)),
                ('is_escalated', models.BooleanField(db_index=True, default=False)),
                ('escalation_date', models.DateTimeField(blank=True, null=True)),
                ('support_breach_count', models.PositiveIntegerField(default=0)),
                ('manager_breach_count', models.PositiveIntegerField(default=0)),
                ('reassigned_notice', models.CharField(blank=True, help_text='Notice for agent if previous lead was reassigned by manager', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, help_text='Supervising Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_leads', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Customer Support Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('disposition', 'Post-Call Disposition'), ('whatsapp_dispatched', 'WhatsApp Dispatched'), ('reassigned', 'Lead Reassigned'), ('escalated', 'SLA Escalation'), ('note', 'Manual Note'), ('created', 'Lead Created')], default='note', max_length=30)),
                ('disposition', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('awaiting_followup', 'Awaiting Follow-up'), ('completed_followup', 'Completed Follow-up'), ('registered', 'Registered / Converted'), ('not_interested', 'Not Interested'), ('lost', 'Lost / Junk')], max_length=30, null=True)),
                ('call_duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('whatsapp_template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_message_body', models.TextField(blank=True, null=True)),
                ('whatsapp_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
