# Generated by Django 5.2.17 on 2026-09-18 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='language_code',
            field=models.CharField(default='en_US', help_text='Meta language code (e.g. en_US, hi)', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_template_name',
            field=models.CharField(blank=True, help_text='Approved template name in Meta Manager (e.g. hotel_booking_offer)', max_length=100),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(default='en_US', max_length=10)),
                ('rendered_body', models.TextField()),
                ('meta_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
